version: '3.1'
services:
  chatglmeft:
    image: janglichao/chatglmeft:v1
    container_name: chatglmeft
    stdin_open: true
    volumes:
      - /Users/kidd/Documents/Projects/llms/fork_chatglmeft:/home/ChatGLM-Efficient-Tuning/
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 2
#              capabilities: [ gpu ]
